ResourceServer/Controllers/CleaningSpaceController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PresentationLayer;
using PresentationLayer.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ResourceServer.Controllers
{
    public class CleaningSpaceController : Controller
    {
        private DataManager _dataManager;
        private ServiceManager _serviceManager;
        private HttpClient _httpClient;
        private string _url;
        public CleaningSpaceController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _serviceManager = new ServiceManager(dataManager);
            _httpClient = new HttpClient();
            _url = "https://localhost:44372/api/cleaningSpace";
        }

        [HttpGet]
        public async Task<IActionResult> Index(int cleaningSpaceId)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/id?spaceId={cleaningSpaceId}");
            CleaningSpaceApiModel apiModel = JsonConvert.DeserializeObject<CleaningSpaceApiModel>(content);
            CleaningSpaceViewModel viewModel = _serviceManager.CleaningSpaceService.ApiModelToViewModel(apiModel);
            viewModel.Users = apiModel.UserIds
                .Select(uId => _serviceManager.UserService.UserDbModelToView(uId)).ToList();

            return View("Index", viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> CleaningSpaceEditor(int roomId, int cleaningSpaceId = 0)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/editor?spaceId={cleaningSpaceId}");
            var editModel = JsonConvert.DeserializeObject<CleaningSpaceEditModel>(content);
            if (editModel.Id == 0)
            {
                editModel.RoomId = roomId;
            }

            return View("CleaningSpaceEditor", editModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveCleaningSpace(CleaningSpaceEditModel editModel)
        {
            var json = JsonConvert.SerializeObject(editModel);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(_url + "/editor", data);
            string result = await response.Content.ReadAsStringAsync();
            var apiModel = JsonConvert.DeserializeObject<CleaningSpaceApiModel>(result);
            var viewModel = _serviceManager.CleaningSpaceService.ApiModelToViewModel(apiModel);
            return RedirectToAction("Index", new { cleaningSpaceId = viewModel.CleaningSpace.Id });
        }


        [HttpGet]
        public async Task<IActionResult> AddPerson(int cleaningSpaceId)
        {
            var content = await _httpClient.GetStringAsync("https://localhost:44372/api/user");
            var userApiModels = JsonConvert.DeserializeObject<List<UserApiModel>>(content);
            List<UserViewModel> userViewModels = userApiModels
                .Select(apiModel => _serviceManager.UserService
                .UserApiModelToView(apiModel)).ToList();

            content = await _httpClient.GetStringAsync(_url + $"/id?spaceId={cleaningSpaceId}");
            CleaningSpaceApiModel spaceApiModel = JsonConvert.DeserializeObject<CleaningSpaceApiModel>(content);
            CleaningSpaceViewModel spaceViewModel = _serviceManager.CleaningSpaceService.ApiModelToViewModel(spaceApiModel);

            PersonCleaningSpaceModel personCleaningSpaceModel = new PersonCleaningSpaceModel
            {
                CLeaningSpace = spaceViewModel,
                Users = userViewModels,
            };
            return View(personCleaningSpaceModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddPerson(PersonCleaningSpaceModel formModel)
        {
            PersonCleaningSpaceApiModel formApiModel = new PersonCleaningSpaceApiModel
            {
                CleaningSpace = _serviceManager.CleaningSpaceService.GetApiModelFromDb(formModel.CleaningSpaceId),
                SelectedUserId = formModel.SelectedUserId,
            };

            var json = JsonConvert.SerializeObject(formApiModel);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(_url + "/editor/addUser", data);

            var result = await response.Content.ReadAsStringAsync();
            var apiModel = JsonConvert.DeserializeObject<CleaningSpaceApiModel>(result);
            //var viewModel = _serviceManager.CleaningSpaceService.ApiModelToViewModel(apiModel);
            return RedirectToAction("Index", new { cleaningSpaceId = apiModel.Id });
        }
    }
}

ResourceServer/Controllers/RoomController.cs
using BusinessLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PresentationLayer;
using PresentationLayer.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ResourceServer.Controllers
{
    public class RoomController : Controller
    {
        private DataManager _dataManager;
        private ServiceManager _serviceManager;
        private HttpClient _httpClient;
        private string _url;
        public RoomController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _serviceManager = new ServiceManager(dataManager);
            _httpClient = new HttpClient();
            _url = "https://localhost:44372/api/room";
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var content = await _httpClient.GetStringAsync(_url);

            List<RoomApiModel> roomApiList = JsonConvert.DeserializeObject<List<RoomApiModel>>(content);
            List<RoomViewModel> roomList = roomApiList
                .Select(rApi => _serviceManager.RoomService.GetViewModelFromApi(rApi)).ToList();
            return View(roomList);
        }

        [HttpGet]
        public IActionResult RoomByUserId(int userId)
        {
            var room = _serviceManager.RoomService.GetRoomByUser(userId);

            if (room != null)
            {
                RoomViewModel viewModel = _serviceManager.RoomService.RoomDbToViewModel(room.Id);
                return View("Index", viewModel);
            }
            else
            {
                return RedirectToAction("RoomEditor");
            }
        }

        [HttpGet]
        public async Task<IActionResult> RoomByRoomId(int roomId)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/id/{roomId}");
            RoomApiModel apiModel = JsonConvert.DeserializeObject<RoomApiModel>(content);
            RoomViewModel room = _serviceManager.RoomService.GetViewModelFromApi(apiModel);
            return View("Index", room);
        }


        [HttpGet]
        public async Task<IActionResult> RoomEditor(int roomId = 0, int userId = 0)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/roomEditor?roomId={roomId}&userId={userId}");
            RoomEditModel roomEditModel = JsonConvert.DeserializeObject<RoomEditModel>(content);
            roomEditModel.RoomAdminId = userId;

            return View("RoomEditor", roomEditModel);
        }

        [HttpGet]
        [Route("editor/users/{roomId}")]
        public async Task<IActionResult> UsersEditor(int roomId)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/id/{roomId}");
            RoomApiModel apiModel = JsonConvert.DeserializeObject<RoomApiModel>(content);
            RoomViewModel viewModel = _serviceManager.RoomService.GetViewModelFromApi(apiModel);

            return View("UsersEditor", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveRoom(RoomEditModel editModel)
        {
            RoomApiModel apiModel = new RoomApiModel
            {
                Id = editModel.Id,
                Name = editModel.Name,
                RoomAdminId = editModel.RoomAdminId,
            };
            var json = JsonConvert.SerializeObject(apiModel);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(_url + "/save", data);
            string result = await response.Content.ReadAsStringAsync();
            apiModel = JsonConvert.DeserializeObject<RoomApiModel>(result);

            var content = await _httpClient.GetStringAsync($"https://localhost:44372/api/user/id/{editModel.RoomAdminId}");
            var userApiModel = JsonConvert.DeserializeObject<UserApiModel>(content);
            userApiModel.RoomId = apiModel.Id;
            json = JsonConvert.SerializeObject(userApiModel);
            data = new StringContent(json, Encoding.UTF8, "application/json");
            response = await _httpClient.PostAsync("https://localhost:44372/api/user", data);
            result = await response.Content.ReadAsStringAsync();
            userApiModel = JsonConvert.DeserializeObject<UserApiModel>(result);

            RoleApiModel roleApiModel = new RoleApiModel
            {
                Name = RoleType.Admin.ToString(),
                UserId = userApiModel.Id,
                RoomId = apiModel.Id,
            };
            json = JsonConvert.SerializeObject(roleApiModel);
            data = new StringContent(json, Encoding.UTF8, "application/json");
            response = await _httpClient.PostAsync("https://localhost:44372/api/role", data);

            return RedirectToAction("Index", "User", new { userId = userApiModel.Id });
        }

        [HttpGet]
        [Route("delete/{roomId}/{userId}", Name = "Delete")]
        public async Task<IActionResult> DeleteRoom(int roomId, int userId)
        {
            try
            {
                var response = await _httpClient.DeleteAsync(_url + $"/delete/id/{roomId}");
                response.EnsureSuccessStatusCode();
                return RedirectToAction("Index", "User", new { userId });
            }
            catch (HttpRequestException)
            {
                return RedirectToAction("Error", "Home");
            }

        }

        [HttpGet]
        [Route("editor/users/add/{roomId}")]
        public async Task<IActionResult> AddUser(int roomId)
        {
            var content = await _httpClient.GetStringAsync(_url + $"/id/{roomId}");
            RoomApiModel roomApiModel = JsonConvert.DeserializeObject<RoomApiModel>(content);

            content = await _httpClient.GetStringAsync("https://localhost:44372/api/user");
            List<UserApiModel> userApiModels = JsonConvert.DeserializeObject<List<UserApiModel>>(content);

            PersonRoomModel personRoomModel = new PersonRoomModel
            {
                Room = roomApiModel,
                Users = userApiModels,
                RoomId = roomId,
                SelectedUserId = 0,
            };

            return View("AddPersonToRoom", personRoomModel);
        }

        [HttpPost]
        [Route("editor/users/add")]
        public async Task<IActionResult> AddUserPost(PersonRoomModel formModel)
        {
            var content = await _httpClient.GetStringAsync($"https://localhost:44372/api/user/id/{formModel.SelectedUserId}");
            var userApiModel = JsonConvert.DeserializeObject<UserApiModel>(content);
            userApiModel.RoomId = formModel.RoomId;

            var json = JsonConvert.SerializeObject(userApiModel);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            await _httpClient.PostAsync("https://localhost:44372/api/user", data);

            content = await _httpClient.GetStringAsync(_url + $"/id/{formModel.RoomId}");
            RoomApiModel roomApiModel = JsonConvert.DeserializeObject<RoomApiModel>(content);
            RoomViewModel roomViewModel = _serviceManager.RoomService.GetViewModelFromApi(roomApiModel);

            RoleApiModel roleApiModel = new RoleApiModel
            {
                Name = RoleType.User.ToString(),
                UserId = formModel.SelectedUserId,
                RoomId = formModel.RoomId,
            };
            json = JsonConvert.SerializeObject(roleApiModel);
            data = new StringContent(json, Encoding.UTF8, "application/json");
            await _httpClient.PostAsync("https://localhost:44372/api/role", data);

            return RedirectToAction(nameof(UsersEditor), new { roomId = formModel.RoomId });
        }
    }
}

ResourceServer/Views/Room/AddPersonToRoom.cshtml
@using PresentationLayer.Models
@model PersonRoomModel

<div class="text-center py-5">
    <div>
        <h1>Добавить пользователя</h1>
    </div>
    <div>
        <form asp-action="AddUserPost" asp-controller="Room" method="post" class="w-50 mx-auto">
            <input type="hidden" asp-for="RoomId" value="@Model.RoomId" />
            <div>
                <select size="5" asp-for="SelectedUserId" class="form-select">
                    <option disabled>Выберите пользователя</option>
                    @foreach(var user in Model.Users)
                    {
                        if (user.RoomId == null)
                        {
                            <option value="@user.Id">@user.Nickname</option>
                        }
                    }
                </select>
            </div>
            <div>
                
                <button type="submit" class="btn btn-dark">Сохранить</button>
            </div>
        </form>
    </div>
</div>

ResourceServer/Views/Room/Index.cshtml
@using PresentationLayer.Models;
@model RoomViewModel

<div class="text-center py-5">
<div>
	<h1>Комната @Model.Room.Name</h1>
</div>

<div>
	<h2>Места уборки</h2>
	@if (Model.CleaningSpaces != null)
	{
		<ul class="list-group w-25 mx-auto" >
		@foreach(var cleaningSpace in Model.CleaningSpaces)
		{
			<li class="list-group-item"><a asp-action="Index" asp-controller="CleaningSpace" asp-route-cleaningSpaceId="@cleaningSpace.CleaningSpace.Id">@cleaningSpace.CleaningSpace.Name</a></li>
		}
		</ul>
	}
	
	@Html.ActionLink("Добавить место уборки","CleaningSpaceEditor","CleaningSpace", new {roomId = Model.Room.Id,}, new {@classs = "btn btn-default"})
	<br />
	@{
		string currentUserNickname = User.Identity.Name;

		var currentUser = Model.Users.FirstOrDefault(u => u.User.NickName == currentUserNickname);
		
		if (currentUser.User.Id == Model.Room.RoomAdminId)
		{
			@Html.ActionLink("Редактировать комнату","RoomEditor","Room", new {roomId = Model.Room.Id,}, new {@classs = "btn btn-default"}) <br />
			@Html.ActionLink("Редактировать пользователей", "UsersEditor", "Room", new {roomId = Model.Room.Id}, new {@classs = "btn btn-default"})
		}
	}
	
</div>
</div>

ResourceServer/Views/Room/RoomEditor.cshtml
@using PresentationLayer.Models;
@model RoomEditModel


<div class="form signin w-50 m-auto text-center py-5">
	<form asp-action="SaveRoom" asp-controller="Room" method="post">

		@if (Model.Id == 0)
		{
			<h1>Создать комнату</h1>
		}
		else
		{
			<h1>Редактировать информацию о комнате</h1>
		}
		
		<input name="Id" type="hidden" value="@Model.Id"/>
		<input asp-for="RoomAdminId" type="hidden" value="@Model.RoomAdminId" />
		<div>
			<label asp-for="Name"></label>
			<input name="Name" value="@Model.Name" class="form-control"/> <br />
		</div>
		
		<input asp-for="CreatorId" type="hidden" value=@Model.CreatorId />
		
		<button type="submit" class="btn btn-primary">Сохранить</button>
	</form>
</div>

ResourceServer/Views/Room/UsersEditor.cshtml
@using PresentationLayer.Models
@model RoomViewModel

<div class="text-center py-5">
<div>
    <h1>Редактировать пользователей</h1>
</div>

<div>
    <div>
        <ul class="list-group list-group-flush w-25 mx-auto">
            @foreach(var user in Model.Users)
            {
                <li class="list-group-item ">
                    @user.User.NickName <br/> <br/>
                @Html.RouteLink("Удалить",
                new 
                {
                    controller = "User",
                    action="DeleteFromRoom",
                    roomId=Model.Room.Id, 
                    userId=user.User.Id
                }, 
                new 
                {
                    @class = "btn btn-danger"
                })    
                </li> 
            }
        </ul>
    </div>
    <br/>
    <div>
        @Html.ActionLink("Добавить пользователя","AddUser","Room",new{roomId=Model.Room.Id}, new {@class="btn btn-primary"})
    </div>
</div>
</div>